using IronPdf.Engines.Chrome;
using IronPdf;
namespace IronPdf.Examples.HowTo.JavascriptToPdf
{
    public static class Section1
    {
        public static void Run()
        {
            var renderer = new IronPdf.ChromePdfRenderer();
            renderer.RenderingOptions.EnableJavaScript = true;
            renderer.RenderingOptions.WaitFor.JavaScript(5000);

            renderer.RenderHtmlAsPdf("<h1>Start</h1><script>document.write('<h1>Generated by JS</h1>');window.ironpdf.notifyRender();</script>")
                .SaveAs("js-rendered.pdf");
        }
    }
}