<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace></RootNamespace>
		<StartupObject>IronPdf.Examples.GettingStarted.VbNetPdf.Program</StartupObject>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="IronPdf" Version="*" />
	</ItemGroup>
</Project>
